### ISSUE TITLE
Dropdown list opt out for 'enum' parameters

### ISSUE THREAD

**Issue by armab** [StackStorm/st2web#153]
When action parameter is enum in yaml: 

``` yaml
parameters:
  verbose:
    description: "Verbose mode (-vvvv to enable connection debugging)"
    type: string
    enum:
      - v
      - vv
      - vvv
      - vvvv
```

In UI when I select it from dropdown: 
![enum-1](https://cloud.githubusercontent.com/assets/1533818/7784250/b80172de-0167-11e5-8146-90e8456e11dc.gif)

there is no way to opt out (select blank value)
![enum-2](https://cloud.githubusercontent.com/assets/1533818/7784251/b90256e4-0167-11e5-931b-5dda2c6e177a.gif)

Such behavior is useful when parameter is `required`, but for this case when parameter is optional - should be a way to select blank dropdown item.

**Comment by Kami** [comment]
Agreed.

Good catch and thanks for the report.

**Comment by LindsayHill** [comment]
Not sure when it was fixed, but I just tested this with v.2.2.0, and I am able to select a blank value:

![enum](https://cloud.githubusercontent.com/assets/3607046/24013612/3777a290-0a3f-11e7-8c14-83882844df52.png)

That has this metadata:
```
  method:
    description: HTTP method to use.
    enum:
    - HEAD
    - GET
    - POST
    - PUT
    - DELETE
```

So looks like this is OK now
