### ISSUE TITLE
Array Parameter not recognising comma seperated integer items

### ISSUE THREAD

**Issue by paul-mulvihill** [StackStorm/st2web#295]
I'm attempting to use the array parameter type with an items type of integer. Although when i then attempt to input values via the webUI to test the action. It returns an 
"Failed to run action <value before comma> is not of type integer" 
error message appears. It doesn't even actually call the action (not showing in history)

Input in web UI
85001,85002

I have tried the following and all return the same error
[85001,85001]
85001

Yaml config:
```
parameters:
   mid:
      type: "array"
      description: "ICSP MID for desired server. (Comma seperated)"
      required: true
      items:
        type: "integer"
```
