### ISSUE TITLE
Object parameter becomes mandatory if anything is typed in it

### ISSUE THREAD

**Issue by paul-mulvihill** [StackStorm/st2web#296]
once a value is entered into the webui Parameter field of type "object" the field then becomes mandatory and can not be left blank.

This is the yaml setup for what I have experienced this on. I have also noticed it with the env parameter

```
    connection_details:
      type: "object"
      description: "Connection details. eg { \"host\": \"192.168.0.1\", \"user\":\"username\", \"pass\": \"secret\" }"
      required: false
```

If the field is never touched then no problem at all. but once something has entered, even if it's then blanked out, it won't proceed without a valid input.
