### ISSUE TITLE
Overriding required parameter as optional is not respected in UI

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2web#307]
We have a simple action which runs as a remote-shell-cmd. It sets up a default `hosts` value and updates the parameter so that its no longer required.

```
name: "truncate_records"
pack: "sentinel"
description: "Truncate records in Sentinel"
enabled: true

runner_type: "remote-shell-cmd"

parameters:
  cmd:
    default: "/usr/local/bin/sentinel_truncate.py"
    immutable: true
  hosts:
    description: "Host where /usr/local/bin/sentinel_truncate.py is located"
    default: "snowflake01"
    required: false
```

We can see that this the `default` and `required` attributes are successfully updated for the `hosts` field:

```
$ st2 action get sentinel.truncate_records
+-------------+--------------------------------------------------------------+
| Property    | Value                                                        |
+-------------+--------------------------------------------------------------+
| id          | 573b2fc359e5f13274087824                                     |
| uid         | action:sentinel:truncate_records                             |
| ref         | sentinel.truncate_records                                    |
| pack        | sentinel                                                     |
| name        | truncate_records                                             |
| description | Truncate records in Sentinel                                 |
| enabled     | True                                                         |
| entry_point |                                                              |
| runner_type | remote-shell-cmd                                             |
| parameters  | {                                                            |
|             |     "cmd": {                                                 |
|             |         "default": "/usr/local/bin/sentinel_truncate.py"     |
|             |         "immutable": true                                    |
|             |     },                                                       |
|             |     "hosts": {                                               |
|             |         "default": "snowflake01",                            |
|             |         "required": false,                                   |
|             |         "description": "Host where                           |
|             | /usr/local/bin/sentinel_truncate.py is located"              |
|             |     }                                                        |
|             | }                                                            |
| notify      |                                                              |
| tags        |                                                              |
+-------------+--------------------------------------------------------------+
```

We can run it successfully on the CLI without specifying the `hosts` parameter:

```
$ st2 run sentinel.truncate_records
..
id: 573b51be59e5f16cd662ffc3
status: succeeded
parameters: None
result:
  snowflake01:
    failed: false
    return_code: 0
    stderr: ''
    stdout: ''
    succeeded: true
```

But the UI still shows `hosts` as required (adds an asterisk by the name) and doesn't allow us to click "Run" (since its grayed out instead of orange). Once I write something in the `hosts` field, I can click "Run"

However, adding `immutable: true` removes it from the UI and allows you to click "Run" as expected. (This works both with and without `required: false` also present.)
