### ISSUE TITLE
Search operator not in operator dropdown for rules criteria

### ISSUE THREAD

**Issue by ahubl-mz** [StackStorm/st2web#492]
When I added the [`search` operator](https://github.com/StackStorm/st2/pull/3833) to StackStorm, I didn't realize also needed to add it to the web interface (my bad ☹️). So now the `search` operator is supported in YAML files but doesn't show up in the list of operators in the web UI:

![screen shot 2018-01-25 at 12 12 37 pm](https://user-images.githubusercontent.com/32691407/35414124-7151bbd8-01d6-11e8-9af9-456f2a1c879d.png)

Adding this operator is not as straightforward as adding it to the `types` list in `st2web/modules/st2-criteria/criteria.component.js`, since its `pattern` isn't a simple static value, it's a list of subcriteria to match (see my PR above and the [documentation I wrote](https://docs.stackstorm.com/rules.html#advanced-comparison) for it to learn more), so it will have to be a special case.

Thanks!

**Comment by Xorso** [comment]
So I have a few rules that utilize this feature and it looks like it is now breaking the webUI if you try to access that rule. This means I can't enable or disable the rule from the frontend or view it's criteria.

Here is an example of my rule:

```yaml
---
  name: 'deploy'
  pack: 'deploy'
  description: 'Config Ticket'
  enabled: false

  trigger:
      type: 'jira.event'

  criteria:
      trigger.event.body.issue_all.fields.issuetype.name:
        type: "iequals"
        pattern: "Config Console"
      trigger.event.body.changelog.items:
        type: "search"
        condition: any
        pattern:
          item.field:
            type: "iequals"
            pattern: "status"
          item.toString:
            type: "iequals"
            pattern: "Ready for Deploy "

  action:
    ...
```

The error I am getting is a react error visible from the developer console. The page goes completely white when I hit the error. This only happens when I go to actually view the rule in the UI.

```
Unhandled Promise Rejection: Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bitem.toString%2C%20item.field%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

I have tried a couple of different iterations to see if I could get it to work, but it looks like there is no support to handle this.

**Comment by dylan-bitovi** [comment]
Bumping this issue, I am encountering this as well on ST3.5; my rule is even simpler than the one above:
```
  trigger.body.issue.fields.items:
    type: "search"
    condition: any
    pattern:
      item.name:
        type: "equals"
        pattern: "Test"
```
