### ISSUE TITLE
Web UI crashes with "Unable to retrieve execution"

### ISSUE THREAD

**Issue by tintoy** [StackStorm/st2web#520]
Hi.

I have an action which, if there are any executions for it present in history, reliably crashes the web UI's history view with "Unable to retrieve execution xxxx" (more specifically, `TypeError: v.join is not a function`).

### Error

```
Unable to retrieve execution "5ae799f817d51a66ad8e4c84".
main.js:1:1171785
TypeError: v.join is not a function
Stack trace:
toStateValue@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:863937
BaseTextField@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:868008
ArrayField@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:863290
constructClassInstance@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:373996
beginWork@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:376629
d@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:380615
f@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:380939
g@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:381178
m@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:384723
w@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:384460
z@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:383590
u@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:382985
enqueueSetState@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:373429
["/home/circleci/project/node_modules/react/cjs/react.production.min.js"]</A.prototype.setState@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:501563
onStateChange@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:428574
notify@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:448154
notifyNestedSubs@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:447618
onStateChange@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:428601
dispatch@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:513869
promiseMiddleware/</</<@https://stackstorm.st2-demo.tintoy.io/js/main.js:1:1251411
main.js:1:1171829
TypeError: v.join is not a function
```

### Execution details

```
root@st2-host:~# st2 execution list
+--------------------------+---------------------+--------------+-------------------------+---------------------+----------------+
| id                       | action.ref          | context.user | status                  | start_timestamp     | end_timestamp  |
+--------------------------+---------------------+--------------+-------------------------+---------------------+----------------+
| 5ae799f817d51a66ad8e4c84 | jumpbox_demo        | st2admin     | canceled (158s elapsed) | Mon, 30 Apr 2018    | Mon, 30 Apr    |
|                          | .jumpbox-exec       |              |                         | 22:34:32 UTC        | 2018 22:37:10  |
|                          |                     |              |                         |                     | UTC            |
+--------------------------+---------------------+--------------+-------------------------+---------------------+----------------+
```

```
root@st2-host:~# st2 execution get 5ae799f817d51a66ad8e4c84
id: 5ae799f817d51a66ad8e4c84
status: canceled (158s elapsed)
parameters:
  command: hostname
  hosts: '********'
result:
  message: Action canceled by user.
  user: st2admin
```

The problem occurs regardless of the execution status, BTW. If I purge executions from the database, the UI works correctly until I run the action again.

Not sure if it's worth mentioning, but the `hosts` parameter is marked as secret but is a complex property, not a string.

### Action definition

`jumpbox-exec.yaml`:
```yaml
---
name: "jumpbox-exec"
runner_type: "python-script"
description: "Execute commands on a remote system using one or more jumpbox hosts."
enabled: true
entry_point: "jumpbox-exec.py"
parameters:
    command:
        type: "string"
        description: "The commands to execute."
        required: true
        position: 0
    hosts:
        type: "array"
        description: "Details for the target host and any jumpbox hosts used to connect to it (the target host is the last entry)."
        required: true
        secret: true
        position: 1
        items:
            type: "object"
            properties:
                target_ipv4:
                    type: "string"
                    description: "The host's IPV4 address."
                    required: true
                tunnel_local_ipv4:
                    type: "string"
                    description: "The host's local IPV4 address (used when creating the local end of this hop of the SSH tunnel). Can be omitted if it's the same as target_ipv4."
                    required: false
                user:
                    type: "string"
                    description: "The user name for SSH authentication."
                    required: true
                key:
                    type: "string"
                    description: "The private key for SSH authentication."
                    required: true
```

`jumpbox-exec.py`:
```python
#! /usr/bin/env python

import paramiko
import pprint

from st2common.runners.base_action import Action
from StringIO import StringIO

class JumpboxExec(Action):
  def run(self, command, hosts):
    ssh_connection = build_host_chain(hosts)
    (_, stdout, stderr) = ssh_connection.exec_command(command)

    return (True, {
      "stdout": stdout.read().strip(),
      "stderr": stderr.read().strip()
    })

def build_host_chain(hosts):
  hosts.reverse()

  tunnel = None
  while hosts:
      host = hosts.pop()
      target_ipv4 = host['target_ipv4']
      local_ipv4 = host.get('local_ipv4', target_ipv4)
      user = host['user']
      key = paramiko.RSAKey(
        file_obj=StringIO(host['key'])
      )

      print("Connect to host {0} (local_ipv4={1}) as {2} (tunneled={3})...".format(
        target_ipv4,
        local_ipv4,
        user,
        len(hosts) > 0
      ))

      connection = paramiko.SSHClient()
      connection.set_missing_host_key_policy(
        paramiko.AutoAddPolicy()
      )

      if hosts:
        connection.connect(target_ipv4, username=user, pkey=key, sock=tunnel)
        (_, stdout, _) = connection.exec_command('hostname')
        print("Connected to host {0} ({1}).".format(
          target_ipv4,
          stdout.read().strip()
        ))

        # Tunnel through to the next host
        next_host = hosts[len(hosts) - 1]
        next_target_ipv4 = next_host['target_ipv4']
        src_addr = (local_ipv4, 22)
        dest_addr = (next_target_ipv4, 22)
        print("Open tunnel from {0} to {1}...".format(
          local_ipv4,
          next_target_ipv4
        ))
        tunnel = connection.get_transport().open_channel("direct-tcpip", dest_addr, src_addr)
        print("Tunnel connected.")
      else:
        connection.connect(target_ipv4, username=user, pkey=key, sock=tunnel)
        (_, stdout, _) = connection.exec_command('hostname')
        print("Connected to host {0} ({1}).".format(
          target_ipv4,
          stdout.read().strip()
        ))

        return connection
```

May relate to #498.
