### ISSUE TITLE
Inquiry not displaying line breaks as <br>

### ISSUE THREAD

**Issue by guzzijones** [StackStorm/st2web#739]
The inquiry front end should display line breaks in the description of an input property correctly.
`st2 get inquiry [id]` will display embedded line feeds via the cli

action code:

```
version: 1.0
tasks:

  # [877, 193]
  domain:
    action: core.echo
    input:
      message: "{{ctx().indicators.domain|join(\", \")}}"
    next:
      # #fecb2f
      - do:
          - IPv4
        publish:
          - IPv4: "{{ctx().indicators.domain|join(\", \")}}"
  # [864, 311]
  IPv4:
    action: core.echo
    input:
      message: "{{ctx().indicators.IPv4|join(\", \")}}"
    next:
      - do:
          - get_approval

  # [874, 428]
  get_approval:
    action: core.ask
    input:
      ttl: 60
      schema:
        type: object
        properties:
          approved:
            type: boolean
            description: |
                         block all?
                         {% for x in ctx().indicators.domain %}
                         {{x}}
                         {% endfor %}
                         another option to display
                         {{ctx().indicators.domain|join(",  ")}}
            required: True
          color:
            type: string
            description: "what color"
            enum:
              - "blue"
              - "red"

    next:
      - when: <% succeeded() %>
        do: finish
      - when: <% failed() %>
        do: stop

  finish:
    action: core.echo message="Automation completed."

  stop:
    action: core.echo message="Automation stopped."

input:
  - indicators
vars:
  - IPv4: null
  - domain: null
```
