### ISSUE TITLE
Outputs from actions returning false is not shown

### ISSUE THREAD

**Issue by kedare** [StackStorm/st2web#747]
When running an action only returning False, it doesn't show up on the Web UI (like if there was no output)

Example:
```
id: 5ea19d5750944905e623bb92
status: succeeded (1s elapsed)
parameters:
  container: 10.0.0.0/8
  item: 20.0.0.0/24
  item_type: network
  log_level: DEBUG
result:
  exit_code: 0
  result: false
  stderr: ''
  stdout: ''
```

![Screenshot 2020-04-23 at 15 54 11](https://user-images.githubusercontent.com/359877/80107227-1c455980-857b-11ea-8256-d63b7de5252b.png)
