### ISSUE TITLE
Changing pack config from UI corrupts config file

### ISSUE THREAD

**Issue by makandre** [StackStorm/st2web#795]
When I edit a pack's configuration in the UI, I'm seeing 2 problems:

1. Edit the config of any pack, then save.
2. Click to another pack
3. Now go back to the first pack, ALL the fields appear blank (1st problem)
(4. To reproduce the 2nd problem, put values into this blank form and save again)

If I navigate to a completely different section (e.g. History) then come back to the pack's configuration page, then it shows the values.

Things seems to work but I have noticed the config file looks corrupted (2nd problem).  Here's the `kafka.yaml` for the kafka pack as an example:

```
client_id: stackstorm2a
hosts: x.x.x.x:9092
id: 5f1245e6ce51126ac6d608a6
message_sensor:
  client_id: testclientID
  group_id: testgroupID
  hosts: x.x.x.x:9092
  topics:
  - test
pack: kafka
values:
  client_id: StackStorm2
  gcp_message_sensor: {}
  hosts: x.x.x.x:9092
  id: 5f1245e6ce51126ac6d608a6
  message_sensor:
    hosts: x.x.x.x:9092
    topics:
    - test
```

Notice the extra `pack` property and the config repeated under the `values` property.
